### ISSUE TITLE
Implement CLI toolset for juicy elements

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy.github.io#5]
Instead of gulp/grunt/bower bagic and repolepsy hell in merging `-boilerplate` stuff to each and every project, we could provide a set of scripts as npm package, similar to what Polymer does with [polymer-cli](https://www.polymer-project.org/1.0/docs/tools/polymer-cli). We could at least cover:
- init - that provides element boilerplate vanila or polymer one
- bump - that bumps the versions in all files, creates a tag and commit
- test - that executes CLI tests
- serve - runs polyserve
- watch - watch file changes

I would say that first two are crucial.

We can start with just forking `polymer-cli`.

WDYT @warpech?

**Comment by warpech** [comment]
This is now tracked in https://github.com/Starcounter/RebelsLounge/issues/25
